name: TOML and MITRE Validaion

on:

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: 
          python devolopment/validation.py
          python devolopment/mitre.py
